source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ADGCoreDataKit_Example' do
  pod "ADGCoreDataKit", :path => "../"
end

target 'ADGCoreDataKit_Tests' do
  pod "ADGCoreDataKit", :path => "../"

  
end
